### ISSUE TITLE
Mob no longer killable on UE 4.13.1

### ISSUE THREAD

**Issue by wowsuchnamaste** [ThePerfectGame/VIM#4]
The default mob is no longer killable after the upgrade to 4.13.1.

**Comment by wowsuchnamaste** [comment]
UE reports the following error:
`PIE:Warning: Warning VAICharacter_BP_2.CharacterMesh0 SK_Mannequin has to have 'Simulate Physics' enabled if you'd like to AddForceAtLocation. `

However, enabling Simulate Physics on the character mesh "kills" the pawn on launch (although allows for moving around and firing without the pawn... which is weird)

**Comment by wowsuchnamaste** [comment]
From @AuggieTPG - 

> Okay I got the new version up and running on 4.13.2   had a quick look at the bug that's stopping the damage  occurring to player and zombies.  I've tracked it down to VWeaponInstant.cpp  line 83
> I got a return value from the TakeDamage() and output it to log
> 
> `float myFloat = Hit.GetActor()->TakeDamage(ActualHitDamage, DamageEvent, MyPawn->Controller, this);`
> `UE_LOG(LogTemp, Warning, TEXT("Dealing %f damage to %s"),myFloat , *Hit.GetActor()->GetName());`
> 
> this is the result
> 
> `LogTemp:warning: Dealing 26.000000 damage to Wall1`
> `LogTemp:warning: Dealing 0.000000 damage to VAICharacter_BP_2`
> 
> So it's dealing the correct damage to the wall but when it hits the AI Character it returns 0 damage
> went back to 4.12.5  and tried same line getting this output
> 
> `LogTemp:warning: Dealing 26.000000 damage to Wall5`
> `LogTemp:warning: Dealing 26.000000 damage to VAICharacter_BP_3`
> 
> and the AI died
> 
> I had a look through the TakeDamage function located in actor.cpp in versions 4.12 and compared it to  version 4.13  looks identical.

Setting issue to Backlog and removing myself as assignee, as I'm not able to brain today, in case one of you want to take over (please do! :) ) ( @Evandar1974 / @AuggieTPG )

**Comment by AuggieTPG** [comment]
Bug was located and fixed. The issue was that the UE 4 engine code has two versions of  InitNewPlayer(), and the version we were using, is not called automatically when the game is started now as it was in V4.12 .  Switching to the second version of InitNewPlayer() fixed the problem
